// Auto City-Split Database — Top cities for 193+ countries
// Used by the scraper engine to break country-level queries into city-level sub-queries

const CITY_MAP = {
  'afghanistan': ['Kabul', 'Herat', 'Kandahar', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz', 'Ghazni', 'Lashkar Gah', 'Taloqan', 'Puli Khumri'],
  'albania': ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër', 'Fier', 'Korçë', 'Berat', 'Lushnjë', 'Kavajë'],
  'algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Djelfa', 'Sétif', 'Sidi Bel Abbès', 'Biskra'],
  'andorra': ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Sant Julià de Lòria', 'La Massana'],
  'angola': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Lubango', 'Kuito', 'Malanje', 'Namibe', 'Cabinda', 'Uíge'],
  'antigua and barbuda': ['St. Johns', 'All Saints', 'Liberta', 'Potters Village', 'Bolans'],
  'argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'La Plata', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan', 'Neuquén', 'Bahía Blanca', 'Resistencia', 'Corrientes', 'Posadas'],
  'armenia': ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Hrazdan', 'Abovyan', 'Kapan', 'Armavir', 'Artashat', 'Gavar'],
  'australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Hobart', 'Darwin', 'Cairns', 'Wollongong', 'Geelong', 'Townsville', 'Ballarat'],
  'austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn'],
  'azerbaijan': ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Shirvan', 'Nakhchivan', 'Sheki', 'Lankaran', 'Yevlakh', 'Khankendi'],
  'bahamas': ['Nassau', 'Freeport', 'West End', 'Coopers Town', 'Marsh Harbour'],
  'bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town', 'Sitra', 'Budaiya', 'Jidhafs', 'Al Hidd'],
  'bangladesh': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Rangpur', 'Comilla', 'Gazipur', 'Narayanganj', 'Mymensingh', 'Barisal', 'Tongi', 'Jessore', 'Bogra', 'Cox Bazar'],
  'barbados': ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown'],
  'belarus': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest', 'Bobruisk', 'Baranovichi', 'Borisov', 'Pinsk'],
  'belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Mechelen'],
  'belize': ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk', 'Dangriga', 'Corozal'],
  'benin': ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon', 'Kandi', 'Abomey-Calavi', 'Natitingou'],
  'bhutan': ['Thimphu', 'Phuntsholing', 'Paro', 'Punakha', 'Wangdue Phodrang', 'Samdrup Jongkhar'],
  'bolivia': ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'Oruro', 'Tarija', 'Potosí', 'Trinidad', 'Cobija', 'Riberalta'],
  'bosnia and herzegovina': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar', 'Bijeljina', 'Brčko', 'Bihać', 'Prijedor', 'Trebinje'],
  'botswana': ['Gaborone', 'Francistown', 'Molepolole', 'Maun', 'Serowe', 'Selebi-Phikwe', 'Kanye', 'Mahalapye', 'Mogoditshane', 'Mochudi'],
  'brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belém', 'Goiânia', 'Guarulhos', 'Campinas', 'Florianópolis'],
  'brunei': ['Bandar Seri Begawan', 'Tutong', 'Seria', 'Kuala Belait', 'Temburong'],
  'bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen'],
  'burkina faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora', 'Dédougou', 'Kaya', 'Tenkodogo'],
  'burundi': ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi', 'Ruyigi', 'Kayanza', 'Cibitoke'],
  'cabo verde': ['Praia', 'Mindelo', 'Espargos', 'Assomada', 'Santa Maria'],
  'cambodia': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Poipet', 'Kampong Cham', 'Ta Khmau', 'Pursat', 'Kampot', 'Koh Kong'],
  'cameroon': ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua', 'Maroua', 'Ngaoundéré', 'Kumba', 'Nkongsamba', 'Bertoua'],
  'canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Quebec City', 'Halifax', 'Victoria', 'Saskatoon', 'Regina', 'Hamilton', 'Kitchener', 'London Ontario'],
  'central african republic': ['Bangui', 'Bimbo', 'Berbérati', 'Carnot', 'Bambari', 'Bossangoa', 'Bria', 'Bangassou'],
  'chad': ["N'Djamena", 'Moundou', 'Abéché', 'Sarh', 'Kélo', 'Koumra', 'Pala', 'Am Timan'],
  'chile': ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Iquique', 'Puerto Montt', 'La Serena', 'Chillán', 'Osorno', 'Valdivia', 'Punta Arenas'],
  'china': ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Chongqing', 'Nanjing', 'Tianjin', "Xi'an", 'Suzhou', 'Dongguan', 'Shenyang', 'Qingdao'],
  'colombia': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Cúcuta', 'Ibagué', 'Manizales', 'Villavicencio', 'Pasto', 'Armenia', 'Montería'],
  'comoros': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Mitsamiouli'],
  'congo': ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Ouesso', 'Owando', 'Impfondo', 'Madingou'],
  'costa rica': ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia', 'Puntarenas', 'Limón', 'San Isidro', 'Desamparados', 'Nicoya'],
  'croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Pula', 'Slavonski Brod', 'Karlovac', 'Varaždin', 'Dubrovnik'],
  'cuba': ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo', 'Santa Clara', 'Las Tunas', 'Bayamo', 'Cienfuegos', 'Pinar del Río'],
  'cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta', 'Paralimni', 'Kyrenia'],
  'czech republic': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'České Budějovice', 'Hradec Králové', 'Ústí nad Labem', 'Pardubice'],
  'czechia': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'České Budějovice', 'Hradec Králové', 'Ústí nad Labem', 'Pardubice'],
  'denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Roskilde'],
  'djibouti': ['Djibouti City', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil', 'Arta'],
  'dominica': ['Roseau', 'Portsmouth', 'Marigot', 'Berekua', 'Mahaut'],
  'dominican republic': ['Santo Domingo', 'Santiago', 'San Pedro de Macorís', 'La Romana', 'San Cristóbal', 'Puerto Plata', 'San Francisco de Macorís', 'Higüey', 'La Vega', 'Bonao'],
  'dr congo': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Kananga', 'Bukavu', 'Goma', 'Likasi', 'Kolwezi', 'Tshikapa'],
  'east timor': ['Dili', 'Baucau', 'Maliana', 'Suai', 'Lospalos', 'Aileu'],
  'timor-leste': ['Dili', 'Baucau', 'Maliana', 'Suai', 'Lospalos', 'Aileu'],
  'ecuador': ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala', 'Ambato', 'Manta', 'Portoviejo', 'Loja', 'Riobamba', 'Esmeraldas', 'Ibarra', 'Durán', 'Latacunga'],
  'egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'Tanta', 'Asyut', 'Ismailia', 'Faiyum', 'Zagazig', 'Aswan', 'Damanhur'],
  'el salvador': ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Santa Tecla', 'Apopa', 'Soyapango', 'Delgado'],
  'equatorial guinea': ['Malabo', 'Bata', 'Ebebiyín', 'Aconibe', 'Evinayong', 'Mongomo'],
  'eritrea': ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera', 'Adi Keyh', 'Barentu', 'Dekemhare'],
  'estonia': ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve', 'Viljandi', 'Rakvere', 'Maardu', 'Sillamäe', 'Kuressaare'],
  'eswatini': ['Mbabane', 'Manzini', 'Big Bend', 'Malkerns', 'Nhlangano', 'Siteki', 'Piggs Peak'],
  'ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Adama', 'Hawassa', 'Bahir Dar', 'Jimma', 'Dessie', 'Jijiga', 'Harar', 'Shashamane'],
  'fiji': ['Suva', 'Nadi', 'Lautoka', 'Labasa', 'Ba', 'Levuka', 'Sigatoka', 'Savusavu'],
  'finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori'],
  'france': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Toulon', 'Saint-Étienne', 'Le Havre'],
  'gabon': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga'],
  'gambia': ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni', 'Lamin', 'Sukuta', 'Gunjur'],
  'georgia': ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi', 'Zugdidi', 'Gori', 'Poti', 'Kobuleti', 'Samtredia', 'Senaki'],
  'germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Bremen', 'Dresden', 'Hanover', 'Nuremberg', 'Duisburg'],
  'ghana': ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Ashaiman', 'Tema', 'Cape Coast', 'Sekondi', 'Obuasi', 'Sunyani', 'Koforidua', 'Ho', 'Wa', 'Bolgatanga'],
  'greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos', 'Ioannina', 'Chania', 'Kavala', 'Rhodes', 'Kalamata', 'Corfu', 'Alexandroupoli', 'Serres'],
  'grenada': ['St. Georges', 'Gouyave', 'Grenville', 'Sauteurs', 'Victoria'],
  'guatemala': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Escuintla', 'Petapa', 'San Miguel Petapa', 'Chinautla', 'Cobán', 'Huehuetenango'],
  'guinea': ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labé', 'Mamou', 'Guéckédou', 'Boké', 'Siguiri', 'Kissidougou'],
  'guinea-bissau': ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama', 'Cacheu', 'Bubaque', 'Catió'],
  'guyana': ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina', 'Bartica', 'Corriverton'],
  'haiti': ['Port-au-Prince', 'Cap-Haïtien', 'Delmas', 'Gonaïves', 'Les Cayes', 'Pétion-Ville', 'Jacmel', 'Jérémie'],
  'honduras': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso', 'Comayagua', 'Choluteca', 'Danlí', 'Siguatepeque'],
  'hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely'],
  'iceland': ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær', 'Garðabær', 'Mosfellsbær', 'Selfoss'],
  'india': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow', 'Surat', 'Chandigarh', 'Indore', 'Nagpur', 'Kochi', 'Goa', 'Bhopal', 'Vadodara', 'Coimbatore', 'Noida'],
  'indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Tangerang', 'Depok', 'Denpasar', 'Yogyakarta', 'Batam', 'Malang', 'Manado', 'Balikpapan'],
  'iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz', 'Qom', 'Ahvaz', 'Kermanshah', 'Urmia', 'Rasht', 'Kerman', 'Zahedan', 'Hamadan', 'Yazd'],
  'iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Najaf', 'Karbala', 'Kirkuk', 'Nasiriyah', 'Amarah', 'Duhok', 'Hillah', 'Diwaniyah', 'Kut', 'Samarra'],
  'ireland': ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kilkenny', 'Drogheda', 'Dundalk', 'Sligo', 'Athlone', 'Wexford', 'Letterkenny', 'Tralee', 'Ennis', 'Carlow', 'Naas', 'Mullingar', 'Bray', 'Navan', 'Newbridge'],
  'israel': ['Tel Aviv', 'Jerusalem', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beersheba', 'Holon', 'Bnei Brak', 'Ramat Gan', 'Herzliya', 'Kfar Saba', 'Rehovot'],
  'italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Catania', 'Bari', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste'],
  'ivory coast': ['Abidjan', 'Bouaké', 'Yamoussoukro', 'Daloa', 'Korhogo', 'San-Pédro', 'Man', 'Divo', 'Gagnoa', 'Abengourou'],
  'jamaica': ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore', 'Mandeville', 'May Pen', 'Old Harbour', 'Ocho Rios', 'Savanna-la-Mar'],
  'japan': ['Tokyo', 'Osaka', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Saitama', 'Hiroshima', 'Sendai', 'Chiba', 'Kitakyushu', 'Shizuoka'],
  'jordan': ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Aqaba', 'Salt', 'Madaba', 'Mafraq', 'Jerash', 'Karak'],
  'kazakhstan': ['Almaty', 'Astana', 'Shymkent', 'Karaganda', 'Aktobe', 'Taraz', 'Pavlodar', 'Ust-Kamenogorsk', 'Semey', 'Atyrau', 'Kostanay', 'Oral', 'Aktau', 'Petropavlovsk', 'Kyzylorda'],
  'kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Nyeri', 'Machakos', 'Meru', 'Lamu', 'Nanyuki'],
  'kiribati': ['Tarawa', 'Betio', 'Bikenibeu', 'Bairiki'],
  'kuwait': ['Kuwait City', 'Hawalli', 'Salmiya', 'Jahra', 'Farwaniya', 'Fahaheel', 'Mangaf', 'Ahmadi'],
  'kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok', 'Uzgen', 'Balykchy', 'Kara-Balta', 'Naryn', 'Talas'],
  'laos': ['Vientiane', 'Savannakhet', 'Pakse', 'Luang Prabang', 'Thakhek', 'Vang Vieng', 'Phonsavan', 'Xam Neua'],
  'latvia': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera', 'Ogre', 'Tukums'],
  'lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh', 'Byblos', 'Zahle', 'Baalbek', 'Batroun', 'Beiteddine'],
  'lesotho': ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', 'Mohale Hoek', 'Quthing', 'Qacha Nek', 'Butha-Buthe'],
  'liberia': ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper', 'Buchanan', 'Voinjama', 'Zwedru'],
  'libya': ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Al Khums', 'Zliten', 'Zawiya', 'Ajdabiya', 'Sabha', 'Sirte'],
  'liechtenstein': ['Vaduz', 'Schaan', 'Triesen', 'Balzers', 'Eschen', 'Mauren'],
  'lithuania': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus', 'Marijampolė', 'Mažeikiai', 'Jonava', 'Utena'],
  'luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck', 'Diekirch', 'Wiltz', 'Echternach'],
  'madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Ambovombe'],
  'malawi': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Kasungu', 'Mangochi', 'Karonga', 'Salima', 'Nkhotakota', 'Dedza'],
  'malaysia': ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Kuching', 'Kota Kinabalu', 'Malacca', 'Seremban', 'Subang Jaya', 'Kuantan', 'Alor Setar', 'Miri', 'Sibu'],
  'maldives': ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo', 'Naifaru'],
  'mali': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Kayes', 'Ségou', 'Gao', 'Timbuktu', 'Kidal'],
  'malta': ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Żabbar', 'San Ġwann', 'Sliema', 'Naxxar', 'St. Julians'],
  'marshall islands': ['Majuro', 'Ebeye', 'Jaluit', 'Wotje', 'Arno'],
  'mauritania': ['Nouakchott', 'Nouadhibou', 'Néma', 'Kaédi', 'Rosso', 'Zouérat', 'Kiffa', 'Atar'],
  'mauritius': ['Port Louis', 'Vacoas-Phoenix', 'Beau Bassin-Rose Hill', 'Curepipe', 'Quatre Bornes', 'Triolet', 'Goodlands', 'Centre de Flacq'],
  'mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Cancún', 'Mérida', 'Querétaro', 'San Luis Potosí', 'Chihuahua', 'Aguascalientes', 'Morelia', 'Toluca', 'Oaxaca'],
  'micronesia': ['Palikir', 'Weno', 'Kolonia', 'Tofol', 'Colonia'],
  'moldova': ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Comrat', 'Cahul', 'Ungheni', 'Soroca', 'Orhei', 'Edineț'],
  'monaco': ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'],
  'mongolia': ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan', 'Mörön', 'Ölgii', 'Khovd', 'Bayankhongor', 'Dalanzadgad'],
  'montenegro': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Budva', 'Bar', 'Bijelo Polje', 'Kotor', 'Cetinje', 'Ulcinj', 'Tivat'],
  'morocco': ['Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Tangier', 'Agadir', 'Meknes', 'Oujda', 'Kenitra', 'Tetouan', 'Nador', 'El Jadida', 'Beni Mellal', 'Safi', 'Essaouira'],
  'mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Nacala', 'Quelimane', 'Tete', 'Lichinga', 'Pemba'],
  'myanmar': ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago', 'Pathein', 'Monywa', 'Meiktila', 'Myitkyina', 'Taunggyi'],
  'namibia': ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Rundu', 'Oshakati', 'Katima Mulilo', 'Rehoboth', 'Otjiwarongo', 'Keetmanshoop', 'Tsumeb'],
  'nauru': ['Yaren', 'Denigomodu', 'Aiwo', 'Buada'],
  'nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj', 'Dharan', 'Bharatpur', 'Janakpur', 'Butwal', 'Hetauda', 'Bhaktapur', 'Dhangadhi', 'Nepalgunj'],
  'netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Tilburg', 'Almere', 'Breda', 'Nijmegen', 'Arnhem', 'Haarlem', 'Enschede', 'Maastricht', 'Leiden'],
  'new zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin', 'Napier', 'Palmerston North', 'Nelson', 'Rotorua', 'New Plymouth', 'Whangarei', 'Invercargill', 'Queenstown'],
  'nicaragua': ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega', 'Estelí', 'Granada', 'Jinotega', 'Bluefields'],
  'niger': ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez', 'Dosso', 'Diffa', 'Tillabéri'],
  'nigeria': ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Kaduna', 'Maiduguri', 'Zaria', 'Aba', 'Jos', 'Ilorin', 'Oyo', 'Enugu', 'Abeokuta', 'Warri', 'Calabar', 'Uyo', 'Owerri', 'Sokoto'],
  'north korea': ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan', 'Sinuiju', 'Kaesong', 'Sariwon', 'Haeju'],
  'north macedonia': ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Ohrid', 'Veles', 'Štip', 'Strumica', 'Gostivar'],
  'norway': ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg', 'Bodø', 'Ålesund', 'Sandefjord', 'Haugesund'],
  'oman': ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur', 'Ibri', 'Seeb', 'Barka', 'Rustaq', 'Ibra'],
  'pakistan': ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Quetta', 'Sialkot', 'Hyderabad', 'Gujranwala', 'Bahawalpur', 'Sargodha', 'Sukkur', 'Abbottabad'],
  'palau': ['Ngerulmud', 'Koror', 'Airai', 'Meyungs'],
  'palestine': ['Ramallah', 'Gaza', 'Hebron', 'Nablus', 'Bethlehem', 'Jenin', 'Tulkarm', 'Jericho', 'Khan Yunis', 'Rafah'],
  'panama': ['Panama City', 'San Miguelito', 'Colón', 'David', 'La Chorrera', 'Santiago', 'Chitré', 'Penonomé', 'Bocas del Toro'],
  'papua new guinea': ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen', 'Madang', 'Wewak', 'Goroka', 'Kokopo', 'Kimbe'],
  'paraguay': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá', 'Lambaré', 'Fernando de la Mora', 'Encarnación', 'Pedro Juan Caballero', 'Caaguazú'],
  'peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Huancayo', 'Tacna', 'Chimbote', 'Pucallpa', 'Ica', 'Juliaca', 'Cajamarca', 'Ayacucho'],
  'philippines': ['Manila', 'Quezon City', 'Davao', 'Cebu City', 'Zamboanga', 'Taguig', 'Antipolo', 'Pasig', 'Cagayan de Oro', 'Makati', 'Parañaque', 'Bacolod', 'General Santos', 'Iloilo', 'Baguio'],
  'poland': ['Warsaw', 'Kraków', 'Wrocław', 'Łódź', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice', 'Białystok', 'Gdynia', 'Częstochowa', 'Radom', 'Toruń'],
  'portugal': ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Funchal', 'Amadora', 'Almada', 'Setúbal', 'Aveiro', 'Faro', 'Viseu', 'Évora', 'Guimarães', 'Leiria'],
  'qatar': ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal', 'Mesaieed', 'Dukhan', 'Al Shamal'],
  'romania': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea', 'Sibiu', 'Arad', 'Baia Mare', 'Buzău', 'Pitești'],
  'russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Omsk', 'Rostov-on-Don', 'Ufa', 'Krasnoyarsk', 'Voronezh', 'Perm', 'Volgograd'],
  'rwanda': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kibungo', 'Kibuye'],
  'saint kitts and nevis': ['Basseterre', 'Charlestown', 'Sandy Point Town', 'Dieppe Bay Town'],
  'saint lucia': ['Castries', 'Vieux Fort', 'Soufrière', 'Micoud', 'Gros Islet', 'Dennery'],
  'saint vincent and the grenadines': ['Kingstown', 'Georgetown', 'Barrouallie', 'Bequia', 'Layou'],
  'samoa': ['Apia', 'Vaitele', 'Faleula', 'Siusega', 'Faleasiu'],
  'san marino': ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'],
  'sao tome and principe': ['São Tomé', 'Santo Amaro', 'Neves', 'Santana', 'Trindade'],
  'saudi arabia': ['Riyadh', 'Jeddah', 'Makkah', 'Madinah', 'Dammam', 'Khobar', 'Tabuk', 'Abha', 'Taif', 'Buraidah', 'Jizan', 'Najran', 'Jubail', 'Yanbu', 'Hail'],
  'senegal': ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Kaolack', 'Saint-Louis', 'Ziguinchor', 'Mbour', 'Tambacounda', 'Kolda'],
  'serbia': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo', 'Čačak', 'Novi Pazar', 'Kraljevo'],
  'seychelles': ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Anse Royale', 'Takamaka'],
  'sierra leone': ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu', 'Lunsar', 'Port Loko', 'Kambia'],
  'singapore': ['Singapore CBD', 'Orchard', 'Jurong', 'Tampines', 'Woodlands', 'Bukit Merah', 'Toa Payoh', 'Clementi', 'Bedok', 'Sengkang'],
  'slovakia': ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava', 'Trenčín', 'Martin', 'Poprad'],
  'slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Velenje', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Kamnik'],
  'solomon islands': ['Honiara', 'Auki', 'Gizo', 'Buala', 'Tulagi', 'Kirakira'],
  'somalia': ['Mogadishu', 'Hargeisa', 'Kismayo', 'Marka', 'Berbera', 'Baidoa', 'Burao', 'Bosaso', 'Galkayo', 'Garowe'],
  'south africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Polokwane', 'Nelspruit', 'Kimberley', 'Pietermaritzburg', 'Rustenburg', 'Stellenbosch', 'George'],
  'south korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam', 'Goyang', 'Yongin', 'Bucheon', 'Cheongju', 'Jeonju'],
  'south sudan': ['Juba', 'Malakal', 'Wau', 'Bor', 'Rumbek', 'Yei', 'Aweil', 'Bentiu', 'Torit'],
  'spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao', 'Alicante', 'Córdoba', 'Valladolid', 'Vigo', 'Gijón'],
  'sri lanka': ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Batticaloa', 'Trincomalee', 'Anuradhapura', 'Ratnapura', 'Matara', 'Kurunegala', 'Badulla'],
  'sudan': ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'El Obeid', 'Wad Madani', 'Gedaref', 'Nyala', 'Al-Fashir', 'Atbara'],
  'suriname': ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Albina', 'Brokopondo'],
  'sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Örebro', 'Västerås', 'Helsingborg', 'Norrköping', 'Jönköping', 'Lund', 'Umeå', 'Gävle', 'Sundsvall', 'Karlstad'],
  'switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel', 'Thun', 'Fribourg'],
  'syria': ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Raqqa', 'Deir ez-Zor', 'Tartus', 'Idlib', 'Daraa'],
  'taiwan': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Taoyuan', 'Keelung', 'Changhua', 'Pingtung', 'Chiayi', 'Yilan', 'Hualien'],
  'tajikistan': ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar', 'Istaravshan', 'Vahdat', 'Khorugh', 'Tursunzoda', 'Panjakent', 'Isfara'],
  'tanzania': ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Arusha', 'Mbeya', 'Morogoro', 'Tanga', 'Zanzibar City', 'Kigoma', 'Iringa', 'Tabora', 'Moshi'],
  'thailand': ['Bangkok', 'Chiang Mai', 'Pattaya', 'Nonthaburi', 'Nakhon Ratchasima', 'Phuket', 'Hat Yai', 'Udon Thani', 'Khon Kaen', 'Chiang Rai', 'Surat Thani', 'Hua Hin', 'Krabi', 'Ayutthaya', 'Samut Prakan'],
  'togo': ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé', 'Bassar', 'Tsévié', 'Dapaong'],
  'tonga': ['Nukualofa', 'Neiafu', 'Haveluliku', 'Vaini', 'Pangai'],
  'trinidad and tobago': ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima', 'Point Fortin', 'Scarborough', 'Tunapuna', 'Sangre Grande'],
  'tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Gabès', 'Bizerte', 'Monastir', 'Ariana', 'Gafsa', 'Nabeul', 'Hammamet'],
  'turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya', 'Mersin', 'Diyarbakır', 'Kayseri', 'Eskişehir', 'Samsun', 'Trabzon', 'Denizli'],
  'turkmenistan': ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary', 'Balkanabat', 'Bayramaly', 'Türkmenbaşy', 'Tejen', 'Abadan'],
  'tuvalu': ['Funafuti', 'Nanumanga', 'Niulakita', 'Vaitupu'],
  'uganda': ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Mbale', 'Mukono', 'Kasese', 'Masaka', 'Entebbe', 'Fort Portal', 'Soroti', 'Arua', 'Hoima'],
  'ukraine': ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Mykolaiv', 'Mariupol', 'Luhansk', 'Vinnytsia', 'Poltava', 'Chernihiv', 'Kherson', 'Rivne'],
  'uae': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Al Ain', 'Umm Al Quwain'],
  'united arab emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Al Ain', 'Umm Al Quwain'],
  'uk': ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool', 'Edinburgh', 'Bristol', 'Sheffield', 'Newcastle', 'Nottingham', 'Cardiff', 'Belfast', 'Leicester', 'Brighton', 'Southampton', 'Oxford', 'Cambridge', 'Aberdeen', 'York'],
  'united kingdom': ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool', 'Edinburgh', 'Bristol', 'Sheffield', 'Newcastle', 'Nottingham', 'Cardiff', 'Belfast', 'Leicester', 'Brighton', 'Southampton', 'Oxford', 'Cambridge', 'Aberdeen', 'York'],
  'england': ['London', 'Manchester', 'Birmingham', 'Leeds', 'Liverpool', 'Bristol', 'Sheffield', 'Newcastle', 'Nottingham', 'Leicester', 'Brighton', 'Southampton', 'Oxford', 'Cambridge', 'York', 'Bath', 'Exeter', 'Norwich', 'Plymouth', 'Derby'],
  'scotland': ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee', 'Inverness', 'Perth', 'Stirling', 'Kilmarnock', 'Paisley', 'Ayr', 'Falkirk', 'Dumfries'],
  'wales': ['Cardiff', 'Swansea', 'Newport', 'Wrexham', 'Barry', 'Neath', 'Bridgend', 'Cwmbran', 'Llanelli', 'Pontypridd', 'Aberystwyth', 'Bangor'],
  'northern ireland': ['Belfast', 'Derry', 'Lisburn', 'Newry', 'Bangor', 'Craigavon', 'Ballymena', 'Newtownabbey', 'Carrickfergus', 'Omagh'],
  'usa': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Miami', 'Denver', 'Seattle', 'Atlanta', 'Boston', 'Portland', 'Las Vegas', 'Nashville', 'Detroit'],
  'united states': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Miami', 'Denver', 'Seattle', 'Atlanta', 'Boston', 'Portland', 'Las Vegas', 'Nashville', 'Detroit'],
  'us': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Miami', 'Denver', 'Seattle', 'Atlanta', 'Boston', 'Portland', 'Las Vegas', 'Nashville', 'Detroit'],
  'america': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Miami', 'Denver', 'Seattle', 'Atlanta', 'Boston', 'Portland', 'Las Vegas', 'Nashville', 'Detroit'],
  'uruguay': ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembó', 'Melo', 'Mercedes', 'Artigas'],
  'uzbekistan': ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan', 'Andijan', 'Nukus', 'Fergana', 'Karshi', 'Kokand', 'Margilan', 'Jizzakh', 'Navoi', 'Termez', 'Urgench', 'Gulistan'],
  'vanuatu': ['Port Vila', 'Luganville', 'Norsup', 'Isangel', 'Sola', 'Lakatoro'],
  'vatican city': ['Vatican City'],
  'venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'Barcelona', 'Maturín', 'San Cristóbal', 'Ciudad Bolívar', 'Mérida', 'Barinas', 'Cumaná', 'Punto Fijo'],
  'vietnam': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Biên Hòa', 'Nha Trang', 'Huế', 'Buôn Ma Thuột', 'Vũng Tàu', 'Quy Nhon', 'Long Xuyên', 'Thai Nguyen', 'Vinh', 'Nam Dinh'],
  'yemen': ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb', 'Dhamar', 'Mukalla', 'Seiyun', 'Zinjibar', 'Sayyan'],
  'zambia': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Livingstone', 'Chingola', 'Mufulira', 'Luanshya', 'Kasama', 'Chipata', 'Solwezi', 'Mansa'],
  'zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Masvingo', 'Kwekwe', 'Kadoma', 'Chinhoyi', 'Victoria Falls'],

  // --- MAJOR GLOBAL CITIES & METROPOLITAN NEIGHBORHOODS ---
  'london': ['London Central', 'London Soho', 'London Camden', 'London Westminster', 'London Kensington', 'London Shoreditch', 'London Greenwich', 'London Islington', 'London Chelsea', 'London Brixton', 'London Clapham', 'London Mayfair', 'London Canary Wharf', 'London Stratford', 'London Richmond', 'London Hackney', 'London Hammersmith', 'London Fulham', 'London Battersea', 'London Wimbledon', 'London Paddington', 'London Southwark', 'London Covent Garden', 'London Notting Hill', 'London Holborn', 'London Marylebone'],
  'new york': ['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island', 'SoHo NYC', 'Tribeca', 'Williamsburg Brooklyn', 'Harlem', 'Midtown Manhattan', 'Lower East Side', 'Upper East Side', 'Upper West Side', 'Astoria Queens', 'DUMBO Brooklyn', 'Chelsea NYC', 'Greenwich Village', 'Bushwick'],
  'nyc': ['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island', 'SoHo NYC', 'Tribeca', 'Williamsburg Brooklyn', 'Harlem', 'Midtown Manhattan', 'Lower East Side', 'Upper East Side', 'Upper West Side', 'Astoria Queens', 'DUMBO Brooklyn', 'Chelsea NYC', 'Greenwich Village', 'Bushwick'],
  'dublin': ['Dublin City Centre', 'Dublin Temple Bar', 'Dublin Docklands', 'Dublin Ranelagh', 'Dublin Rathmines', 'Dublin Ballsbridge', 'Dublin Swords', 'Dublin Dun Laoghaire', 'Dublin Clontarf', 'Dublin Blackrock', 'Dublin Malahide', 'Dublin Dundrum', 'Dublin Tallaght'],
  'paris': ['Paris 1er', 'Paris Marais', 'Paris Montmartre', 'Paris Bastille', 'Paris Saint-Germain', 'Paris Quartier Latin', 'Paris Champs-Elysees', 'Paris Belleville', 'Paris Montparnasse', 'Paris Oberkampf', 'Paris Canal Saint-Martin', 'Paris Bercy', 'Paris La Defense'],
  'mumbai': ['South Mumbai', 'Bandra', 'Andheri', 'Juhu', 'Colaba', 'Dadar', 'Worli', 'Lower Parel', 'BKC Mumbai', 'Powai', 'Malad', 'Borivali', 'Goregaon', 'Thane', 'Navi Mumbai'],
  'delhi': ['Connaught Place', 'South Extension', 'Hauz Khas', 'Saket', 'Karol Bagh', 'Lajpat Nagar', 'Dwarka Delhi', 'Rohini', 'Vasant Kunj', 'Chandni Chowk', 'Rajouri Garden', 'Noida', 'Gurugram'],
  'bangalore': ['Koramangala', 'Indiranagar', 'HSR Layout', 'Whitefield', 'Jayanagar', 'MG Road Bangalore', 'Electronic City', 'JP Nagar', 'Marathahalli', 'Malleshwaram'],
  'bengaluru': ['Koramangala', 'Indiranagar', 'HSR Layout', 'Whitefield', 'Jayanagar', 'MG Road Bangalore', 'Electronic City', 'JP Nagar', 'Marathahalli', 'Malleshwaram'],
  'sydney': ['Sydney CBD', 'Surry Hills', 'Bondi', 'Manly', 'Newtown Sydney', 'Parramatta', 'Paddington Sydney', 'Darlinghurst', 'Chatswood', 'Coogee', 'Cronulla'],
  'melbourne': ['Melbourne CBD', 'Fitzroy', 'Carlton', 'St Kilda', 'South Yarra', 'Brunswick Melbourne', 'Richmond Melbourne', 'Prahran', 'Southbank Melbourne', 'Docklands Melbourne'],
  'toronto': ['Downtown Toronto', 'Yorkville Toronto', 'Queen Street West', 'The Annex Toronto', 'Distillery District', 'Scarborough', 'North York', 'Etobicoke', 'Mississauga'],
  'chicago': ['Chicago Loop', 'Lincoln Park', 'Wicker Park', 'River North Chicago', 'West Loop Chicago', 'Lakeview Chicago', 'Logan Square', 'Hyde Park Chicago'],
  'los angeles': ['Downtown LA', 'Hollywood', 'Santa Monica', 'Venice LA', 'Beverly Hills', 'Silver Lake', 'West Hollywood', 'Pasadena', 'Culver City', 'Koreatown LA'],
  'la': ['Downtown LA', 'Hollywood', 'Santa Monica', 'Venice LA', 'Beverly Hills', 'Silver Lake', 'West Hollywood', 'Pasadena', 'Culver City', 'Koreatown LA'],
  'dubai': ['Downtown Dubai', 'Dubai Marina', 'Jumeirah', 'Business Bay', 'Deira Dubai', 'Al Barsha', 'JLT Dubai', 'Palm Jumeirah', 'Al Karama', 'Bur Dubai'],
  'berlin': ['Mitte Berlin', 'Kreuzberg', 'Friedrichshain', 'Prenzlauer Berg', 'Neukölln', 'Charlottenburg', 'Schöneberg', 'Wedding Berlin'],
  'amsterdam': ['Amsterdam Centrum', 'Amsterdam Jordaan', 'Amsterdam De Pijp', 'Amsterdam Oud-West', 'Amsterdam Oost', 'Amsterdam Noord', 'Amsterdam Zuid'],
  'tokyo': ['Shinjuku', 'Shibuya', 'Ginza', 'Roppongi', 'Asakusa', 'Akihabara', 'Ikebukuro', 'Ueno', 'Chiyoda', 'Minato Tokyo', 'Meguro', 'Setagaya'],
  'madrid': ['Centro Madrid', 'Salamanca Madrid', 'Chamberi', 'Malasana', 'Chueca', 'Retiro Madrid', 'La Latina', 'Moncloa', 'Chamartin'],
  'barcelona': ['Eixample', 'Gracia', 'Gothic Quarter', 'El Born', 'Poblenou', 'Poble Sec', 'Sarria', 'Les Corts', 'Sant Antoni'],
  'rome': ['Trastevere', 'Monti Rome', 'Centro Storico Rome', 'Prati', 'Testaccio', 'San Lorenzo Rome', 'Flaminio', 'Parioli'],
  'singapore': ['Orchard Singapore', 'Marina Bay', 'Chinatown Singapore', 'Tanjong Pagar', 'Bugis', 'Tiong Bahru', 'Katong', 'Jurong', 'Woodlands Singapore', 'Tampines'],
  'hong kong': ['Central HK', 'Wan Chai', 'Causeway Bay', 'Tsim Sha Tsui', 'Mong Kok', 'Sheung Wan', 'Kennedy Town', 'Kowloon', 'Quarry Bay']
};

module.exports = CITY_MAP;
